version: "3.7"
services:
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/nginx.dockerfile
    ports:
      - 8080:80
    links:
      - php
    depends_on:
      - db
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../src/public:/var/www/htdocs
     
  php:
    build: 
      context: .
      dockerfile: ./php/php.dockerfile
    ports:
      - 9000:9000
    links:
      - db
    depends_on:
      - db
    volumes:
      - ../src:/var/www
      - ../src/public:/var/www/htdocs
      
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 13306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./mysql:/docker-entrypoint-initdb.d