CREATE DATABASE foo;

USE foo;

CREATE TABLE source(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	a INT,
	b INT,
	c INT
);

-- Here we populate the table using a linear congruential generator
INSERT INTO source (a, b, c) SELECT (@n := (13*@n + 97) % 1000003), @n%3, @n%5
FROM   (SELECT @n := FLOOR(RAND() * 1e6) ) init,
			 (SELECT 1 UNION SELECT 2) m01,
			 (SELECT 1 UNION SELECT 2) m02,
			 (SELECT 1 UNION SELECT 2) m03,
			 (SELECT 1 UNION SELECT 2) m04,
			 (SELECT 1 UNION SELECT 2) m05,
			 (SELECT 1 UNION SELECT 2) m06,
			 (SELECT 1 UNION SELECT 2) m07,
			 (SELECT 1 UNION SELECT 2) m08,
			 (SELECT 1 UNION SELECT 2) m09,
			 (SELECT 1 UNION SELECT 2) m10,
			 (SELECT 1 UNION SELECT 2) m11,
			 (SELECT 1 UNION SELECT 2) m12,
			 (SELECT 1 UNION SELECT 2) m13,
			 (SELECT 1 UNION SELECT 2) m14,
			 (SELECT 1 UNION SELECT 2) m15,
			 (SELECT 1 UNION SELECT 2) m16,
			 (SELECT 1 UNION SELECT 2) m17,
			 (SELECT 1 UNION SELECT 2) m18,
			 (SELECT 1 UNION SELECT 2) m19,
			 (SELECT 1 UNION SELECT 2) m20
LIMIT 1000000;